#!/bin/bash

#ASSET_PREFIX="$WORKDIR"/application/resources/assets

#npm install --prefix "$ASSET_PREFIX"
#npm rebuild node-sass

composer install -o --working-dir="$WORKDIR"/application

#php-fpm -D && nginx -g 'daemon off;'
php-fpm -D && nginx

#npm run dev --prefix "$ASSET_PREFIX"
