version: '3'

networks:
  slim4.network:
    driver: bridge

services:
  server:
    build: .
    container_name: "slim4.server"
    restart: unless-stopped
    user: root
    tty: true
    depends_on:
      - postgres
      - redis
    ports:
      - "80:80"
      - "433:433"
      - "9003:9003"
    networks:
      - slim4.network
    volumes:
      - ../server/cache:/etc/nginx/cache
      - ../../:/var/www

  postgres:
    image: bitnami/postgresql:15
    container_name: slim4.postgres
    restart: unless-stopped
    tty: true
    ports:
      - "${DB_PORT:-5432}:5432"
    networks:
      - slim4.network
    volumes:
      - ../postgres:/bitnami/postgresql
    environment:
      - POSTGRESQL_USERNAME=${DB_USERNAME:-root}
      - POSTGRESQL_PASSWORD=${DB_PASSWORD:-root}
      - POSTGRESQL_DATABASE=${DB_NAME:-development}

  pgadmin:
    image: dpage/pgadmin4
    container_name: "slim4.pgadmin"
    tty: true
    depends_on:
      - postgres
    ports:
      - "8080:80"
    networks:
      - slim4.network
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@localhost.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}

  redis:
    image: bitnami/redis:latest
    restart: unless-stopped
    container_name: "slim4.redis"
    tty: true
    ports:
      - '6379:6379'
    networks:
      - slim4.network
    volumes:
      - ../redis:/bitnami/redis/data
    environment:
      - ALLOW_EMPTY_PASSWORD=${REDIS_ALLOW_EMPTY_PASSWORD:-no}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-root}
