version: '3'

networks:
  slim4.network:
    driver: bridge

services:
  server:
    build: .
    container_name: "slim4.server"
    restart: unless-stopped
    user: root
    tty: true
    depends_on:
      - postgres
      - redis
    ports:
      - "80:80"
      - "433:433"
      - "9003:9003"
    networks:
      - slim4.network
    volumes:
      - ../../:/var/www:z
      - ../server/cache:/etc/nginx/cache:z

  #  mariadb:
  #    image: mariadb
  #    container_name: "slim4.mariadb"
  #    restart: unless-stopped
  #    tty: true
  #    ports:
  #      - '3306:3306'
  #    networks:
  #      - slim4.network
  #    volumes:
  #      - ../mysql/config/mariadb.cnf:/etc/mysql/conf.d/custom.cnf:z
  #      - ../mysql/database:/var/lib/mysql:z
  #    environment:
  #      - MYSQL_PASSWORD=root
  #      - MYSQL_ROOT_PASSWORD=root
  #      - MYSQL_DATABASE=development

  #  mysql:
  #    image: mysql:8
  #    container_name: "slim4.mysql"
  #    restart: unless-stopped
  #    tty: true
  #    ports:
  #      - '3306:3306'
  #    networks:
  #      - slim4.network
  #    volumes:
  #      - ../mysql/config/mysql.cnf:/etc/mysql/conf.d/custom.cnf:z
  #      - ../mysql/database:/var/lib/mysql:z
  #    environment:
  #      - MYSQL_PASSWORD=root
  #      - MYSQL_ROOT_PASSWORD=root
  #      - MYSQL_DATABASE=development

  #  phpmyadmin:
  #    image: library/phpmyadmin
  #    container_name: "slim4.phpmyadmin"
  #    restart: unless-stopped
  #    tty: true
  #    depends_on:
  #      - mysql
  #      - mariadb
  #    ports:
  #      - '8080:80'
  #    networks:
  #      - slim4.network
  #    environment:
  #      PMA_USER: root
  #      PMA_PASSWORD: root
  #      PMA_HOSTS: mysql,mariadb
  #      PMA_PORT: 3306
  #      PMA_ARBITRARY: 1

  postgres:
    image: bitnami/postgresql:15
    container_name: slim4.postgres
    restart: unless-stopped
    tty: true
    ports:
      - "${DB_PORT:-5432}:5432"
    networks:
      - slim4.network
    volumes:
      - ../postgres:/bitnami/postgresql
    environment:
      - POSTGRESQL_USERNAME=${DB_USERNAME:-root}
      - POSTGRESQL_PASSWORD=${DB_PASSWORD:-root}
      - POSTGRESQL_DATABASE=${DB_NAME:-development}

  redis:
    image: bitnami/redis:latest
    restart: unless-stopped
    container_name: "slim4.redis"
    tty: true
    ports:
      - '6379:6379'
    networks:
      - slim4.network
    volumes:
      - ../redis:/bitnami/redis/data:z
    environment:
      - ALLOW_EMPTY_PASSWORD=${REDIS_ALLOW_EMPTY_PASSWORD:-no}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-root}
