#!/bin/bash

#npm install --prefix /var/www/app.dev/application/resources/assets
composer install -o --working-dir=/var/www/app.dev/application

php-fpm -D && nginx -g 'daemon off;'
#npm run dev --prefix /var/www/app.dev/application/resources/assets
