#!/usr/bin/env php
<?php

use Core\Bootstrap;
use Symfony\Component\Console\Application;

require_once __DIR__ . '/../public_html/index.php';

try {
  $container = Bootstrap::getApp()->getContainer();
  $application = $container?->get(Application::class);

  exit($application->run());
} catch (Exception $e) {
  dd($e);
}
