#!/usr/bin/env php
<?php

use Core\Application;
use Psr\Container\ContainerInterface;
use Symfony\Component\Console\Application as SymfonyApplication;

require_once __DIR__ . '/../public_html/index.php';

try {
  $container = Application::getApp()->getContainer();

  if (!$container instanceof ContainerInterface) {
    throw new DomainException("Container is not instanceof PSR");
  }

  $application = $container->get(SymfonyApplication::class);

  exit($application->run());
} catch (Throwable $e) {
  dd($e);
}
